### ISSUE TITLE
where is the groundTruth in eval？

### ISSUE THREAD

**Issue by TeslaHua** [1adrianb/binary-face-alignment#14]
When I run in mode=eval mode, main.lua reports an error when it executes utils.calcDistance(predictions,groundTruth). Parsing groundTruth from your code is fileLists in main.lua. . . . The data structure of filesLists does not contain the points member variable. . . . . . So, where is the groundTruth in eval?

**Comment by 1adrianb** [comment]
Hi @TeslaHua,

Unfortunately I don't have a copy of AFLW-PIFA anymore on my computer, you can get one however by contacting the dataset authors. You can however test it on AFLW2000 which is still hosted on my webpage (the script from the instructions contains the link).

Thanks,
Adrian
