### ISSUE TITLE
Error when 'luarocks make'

### ISSUE THREAD

**Issue by jgoenetxea** [1adrianb/binary-face-alignment#3]
I followed the instructions in the README.md file and this error appears:
```
jgoenetxea@Trantor:~/git/binary-face-alignment$ cd bnn.torch/; luarocks make; cd ..;
Error: Argument missing: please specify a rockspec to use on current directory.
```
I am new with lua, and I do not know how to fix this.

**Comment by jgoenetxea** [comment]
Ok, my fault.
I did not initialize the submodules, so the folder was emtpy.

The way to solve this:
```
$ git submodule init
$ git submodule update
```

**Comment by jgoenetxea** [comment]
By the way, the repository path in the README.md file should be 'https://github.com/1adrianb/binary-face-alignment' instead of 'https://github.com/1adrianb/binary-human-pose-estimation'

**Comment by 1adrianb** [comment]
Cloning it with the recursive flag should have cloned the submodules also. 

Thanks for reporting the wrong repo name, I will fix this.
