### ISSUE TITLE
How to convert to bnn.BinarySpatialConvolution from cudnn.SpatialConvolution.cu after training

### ISSUE THREAD

**Issue by stencilman** [1adrianb/binary-face-alignment#4]
(perhaps this is a better place to ask than https://github.com/1adrianb/bnn.torch/issues/2? Sorry for the duplicate!)

Firstly, thank you so much for releasing your code, it helps a lot in understanding your awesome paper!

If I understand the code correctly, for face-alignment, if I want to do everything from the scratch, I have to first train the floating point model using your codebase (https://github.com/1adrianb/face-alignment-training). However, I am missing the link of how you convert this model to the binary model that is available in https://github.com/1adrianb/binary-face-alignment which uses bnn.BinarySpatialConvolution

It seems to me that I need to call the function BinarySpatialConvolution:binarise(convLayer) somehow, but I am a bit confused. Do you have a script which replaces the floating conv modules with their binary counterparts? Do you also train in binary?

I will be very grateful if you can help me out, thanks a lot in advance.

**Comment by 1adrianb** [comment]
Hi @stencilman 
Thanks a lot for you kind words and sorry for the delay. Unfortunatelly the code released for training is for real-valued models only. You can however easily adapt it for the binary case using this: https://github.com/allenai/XNOR-Net (you basically have to do some binarization related things at train time to make them "convertible").
You can binzarize them directly, but without the binarization at train time the performance will be very bad. The function you pointed out can binzarize them corectly only if you trained as described in the XNOR paper.
If you have any other questions, please let me know.
