### ISSUE TITLE
How convert this model to pytorch?

### ISSUE THREAD

**Issue by buliginleo** [1adrianb/binary-face-alignment#9]
Hello!

How convert this model to pytorch or other popular frameworks (caffe, keras, tensorflow)? Opensource converters and pytorch utils can not do this.

**Comment by 1adrianb** [comment]
Hi @buliginleo  The converts will be unable to do this since the code uses custom layers. One will need to port this code: https://github.com/1adrianb/bnn.torch to the desired platform first.

**Comment by aaronchen98** [comment]
Hi@1adrianb
Did you mean I should port the code of custom layers to the pytorch first if I want to convert this model to pytorch?

**Comment by 1adrianb** [comment]
Hi @aaronchen98,

Yes, the layers need to be ported.

**Comment by aaronchen98** [comment]
Hi@1adrianb
Sorry for disturbing you again.
It seems a little difficult for me to convert this model to pytorch.Attually I am in a mess.Shall I just need to make a little change in the 'Binary,lua' and 'BinarySpatialConvolution.lua'?Or I should recode all of '.lua' from 'bnn.torch' using python?
I would appreciate for your any suggestion.
